import { query } from "gitclaw";

// ── Mock Output Data (For Video Demo without API) ────────────────────────────
const MOCK_OUTPUT = `
🔍 [Stack Analyzer] Detecting technology stack...
✅ Found Node.js (v18.x) with Express.js framework.
✅ Detected PostgreSQL and Redis dependencies.
✅ Project structure: routes/api.js, server.js, package.json.

🐳 [Dockerfile Generator] Building multi-stage, non-root Dockerfile...
# --- Dockerfile (Generated by CodeForge) ---
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --quiet
COPY . .
RUN npm run build --if-present

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/server.js ./
COPY --from=builder /app/routes ./routes
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser
HEALTHCHECK --interval=30s --timeout=5s CMD wget -qO- http://localhost:3000/health || exit 1
EXPOSE 3000
CMD ["node", "server.js"]
# --- End of Dockerfile ---

🚀 [CI/CD Pipeline Builder] Generating GitHub Actions...
# --- .github/workflows/ci-cd.yml ---
name: CI/CD Pipeline
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0.15.1
# --- End of Workflow ---

☸️ [K8s Manifest Generator] Applying production-hardening...
✅ Generated Deployment.yaml (runAsNonRoot: true)
✅ Generated Service.yaml (ClusterIP)
✅ Generated NetworkPolicy.yaml (Default Deny Ingress)
✅ Generated HPA.yaml (Auto-scaling enabled)

📊 [Monitoring Setup] Configuring Observability...
✅ Generated Prometheus ServiceMonitor
✅ Generated Alerting Rules (High CPU/Error Rate)

🔒 [Security Auditor] Final Review...
✅ No root users found in Dockerfile.
✅ Resource limits strictly enforced.
✅ Image tags pinned to SHAs.
✅ PASS: Output compliant with CodeForge RULES.md.
`;

// ── Model Selection Logic ───────────────────────────────────────────────────
async function simulateStream(text) {
  const parts = text.split(" ");
  for (const part of parts) {
    process.stdout.write(part + " ");
    await new Promise(r => setTimeout(r, Math.floor(Math.random() * 50) + 10));
  }
}

function resolveModel() {
  // FORCE MOCK MODE with --mock flag
  if (process.argv.includes('--mock')) {
    return "MOCK";
  }

  if (process.env.GEMINI_API_KEY) return "google:gemini-2.0-flash";
  if (process.env.ANTHROPIC_API_KEY) return "anthropic:claude-sonnet-4-5-20250929";
  if (process.env.OPENAI_API_KEY) return "openai:gpt-4o";

  return "MOCK";
}

async function run() {
  const model = resolveModel();
  console.log("🔨 Starting CodeForge AI DevOps Architect...");

  if (model === "MOCK") {
    console.log("⚠️  SIMULATION MODE: Running mock generation for demo video...\n");
    await simulateStream(MOCK_OUTPUT);
  } else {
    console.log(`🔑 Using Provider: ${model}\n`);
    const agentStream = query({
      prompt: "Analyze the sample-project directory and generate complete deployment infrastructure. Do not ask for confirmation.",
      dir: "./",
      model,
    });
    for await (const msg of agentStream) {
      if (msg.type === "delta") process.stdout.write(msg.content);
    }
  }

  console.log("\n\n✅ CodeForge deployment pipeline complete.");
}

run().catch(console.error);
